pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                echo 'finished build'
            }
        }
        stage('frontend test') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install && cd frontend && npm install'
                echo 'finished test'
            }
        }
    }
}
