pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install'
                sh 'cd backend && npm install'
                echo 'finished build'
            }
        }
        stage('frontend test') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                echo 'finished test'
            }
        }
        stage('Backend Tests') {
            agent {
                docker {
                    image 'node:10-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'cd backend && npm run test'
                echo 'Finished backend Tests'
            }
        }
        stage('Code Coverage') {
            agent {
                docker {
                    image 'node:10-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'cd backend && npx istanbul cover /node_modules/mocha/bin/_mocha  __tests__/integration.test.js'
                echo 'Finished backend Tests'
            }
        }
    }
}
