pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                echo 'finished build'
            }
        }
        stage('frontend test') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install'
                sh 'cd frontend'
                sh 'npm install --save @angular/cli'
                sh 'npm install'
                sh 'npm run lint'
                echo 'finished test'
            }
        }
        stage('Backend Tests') {
            agent {
                docker {
                    image 'node:6-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install'
                sh 'cd backend'
                sh 'npm install'
                sh 'npm run test'
                echo 'Finished backend Tests'
            }
        }
    }
}
